name: Fix Code Style

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    # Required by git-auto-commit-action to be able to push the code formatting changes
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.5 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Use GH_PAT if available so the pushed commit can trigger other workflows (like the test suite).
          # Fallback to the default token otherwise.
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fixes coding style"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
