name: Fix Code Style

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'bootstrap/**'
      - 'config/**'
      - 'database/**'
      - 'routes/**'
      - 'tests/**'
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - '.github/workflows/lint.yml'

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        php: [ '8.5' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Setup PHP with Pint
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none
          tools: pint

      - name: Run Pint
        run: pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fixes coding style"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
